export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const REGISTRATION_START = 'LOGIN_START';
export const REGISTRATION_START = 'LOGIN_SUCCESS';
export const REGISTRATION_START = 'LOGIN_ERROR';
export const REGISTRATION_START = 'LOGOUT_START';
export const REGISTRATION_START = 'LOGOUT_SUCCESS';
export const REGISTRATION_START = 'LOGOUT_ERROR';

export const REGISTRATION_START = 'LOGIN_SUCCESS';