//UserActions constants auth and users status detection
export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const UPLOADING_START = 'UPLOADING_START';
export const UPLOADING_END = 'UPLOADING_END';
export const FTECH_ONLINE_USERS_START = 'FTECH_ONLINE_USERS_START';
export const FTECH_ONLINE_USERS_SUCCESS = 'FTECH_ONLINE_USERS_SUCCESS';

//ModelActionsConstans
export const UPLOAD_PROFILE_PICTURE_MODEL_OPEN = 'UPLOAD_PROFILE_PICTURE_MODEL_OPEN';
export const UPLOAD_PROFILE_PICTURE_MODEL_CLOSE = 'UPLOAD_PROFILE_PICTURE_MODEL_CLOSE';

export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
// export const REGISTRATION_START = 'LOGIN_SUCCESS';